### ISSUE TITLE
Delete unused registry packages

### ISSUE THREAD

**Issue by reckseba** [digitalservicebund/ris-norms#297]
We have merged frontend and backend parts into [one combined image](https://github.com/digitalservicebund/ris-norms/pkgs/container/ris-norms).

Therefore delete two two now unused packages before they get outdated and cause risk of people using it:
- [ris-norms/backend](https://github.com/digitalservicebund/ris-norms/pkgs/container/ris-norms%2Fbackend)
- [ris-norms/frontend](https://github.com/digitalservicebund/ris-norms/pkgs/container/ris-norms%2Ffrontend)

**Comment by VictorDelCampo** [comment]
Done
